### ISSUE TITLE
Future of WootzJs

### ISSUE THREAD

**Issue by bertrandchagny** [kswoll/WootzJs#24]
Hello Kirk,
Thank you for your work.
Could you tell us about the future of WootzJs ?

Best regards,
Bertrand

P.S. is it possible to contact you by email ? Thanks

**Comment by kswoll** [comment]
The future of it is that I am not (at the moment) spending a great deal of time with it.  I plan to get back to it in a month or two when I dive back into my XoHoops project which I'm converting to use it.  Most pressingly, I'd like to add Nuget support.  You can find my email on my profile page.
