### ISSUE TITLE
About License Note 

### ISSUE THREAD

**Issue by x335** [kswoll/WootzJs#25]
Hi,
@kswoll 
@kirksqor 

I looked your code.
It is great :+1: 

I but have a question in your License note
Do you write all the code yourself ?
(not use the code from others like Mono or MS?)

especially in WootzJs/WootzJs.Runtime/

sorry for ask that, 
but it's important for me before I can use your code.

Thanks 
X335

**Comment by kswoll** [comment]
Yes, I wrote all the code you in my repo myself (barring a few PRs that you can publicly see in the commit history).

**Comment by x335** [comment]
:+1:  :+1:  :+1: 
Thank you :)
